name: INF 380P Fall 2021

title: INF 380P

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/Chicago

github_repo_url: https://github.com/inf380p/inf380p.github.io
gitter_room: inf380p/fall2021
zoom_url: https://utexas.zoom.us/j/97495200087
canvas_url: https://utexas.instructure.com/courses/1313369

plugins:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Don't serve these files/dirs.
exclude: [vendor, script]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - materials
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

# If this gets archived at a different URL make sure to delete the blank statements at the bottom
baseurl: /fall2021
url: /fall2021

python: true

course:
  title: Introduction to Programming
  number: INF 380P
  instructor: Prof. Elliott Hauser
  ta: Misha Coleman
  semester: Fall 2021
  location: "UTA 1.208"

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: https://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  "Elliott Hauser is an Assistant Professor at the UT Austin iSchool.  He's hacking education as one of the cofounders of Trinket.io."

  MishaCienfuegos:
    name: Misha Coleman
    prof: true
    gravatar:
    website:
    github: MishaCienfuegos
    twitter: mishacienfuegos
    about: "Misha is the course's Teaching Assistant, currently in her second year of the MSIS program at the iSchool. Previously, she worked as a software developer, learning to code on the job. She loves exploring the world by bike! :bike:"

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Turtle"
    github: tommytester
    twitter:
    about: "Testin' course websites since 2014."

  acreese:
    name: acreese
    prof: false
    gravatar:
    website: "#"
    github: acreese
    twitter:
    about: "Here's a little about acreese"

  agunnells:
    name: Ali Gunnells
    prof: false
    gravatar: 
    website: "#"
    github: agunnells
    twitter: AliGunnells
    about: "Ali is in her second year of the dual degree MA/MSIS program in English and information studies at UT-Austin, where she also teaches in the Rhetoric & Writing Dept. and works as a writing consultant at the UWC. Before coming to UT, she was an assistant professor of English at National Louis University. When she isn't in school, Ali loves hanging out with her cat and playing saxophone in two local Austin brass bands."

  alueker:
    name: Andrew Lueker
    prof: false
    gravatar:
    website: "#"
    github: alueker
    twitter:
    about: "Amateur data connoisseur, fan of The Beatles."

  amanda-guerrero:
    name: amanda-guerrero
    prof: false
    gravatar:
    website: "#"
    github: amanda-guerrero
    twitter:
    about: "Amanda is in her first year of the MSIS program at the UT Austin iSchool"

  apurva-shah515:
    name: apurva-shah515
    prof: false
    gravatar:
    website: https://apurvashah1897.myportfolio.com/
    github: apurva-shah515
    twitter:
    about: "2nd Year in the MSIS program, looking to learn more about Python. Also interested in other languages like React and JavaScript!"

  areiter18:
    name: areiter18
    prof: false
    gravatar:
    website: https://www.linkedin.com/in/andrew-reiter-6930a8223/
    github: areiter18
    twitter:
    about: "Andrew is a first year MSIS student studying Digital Archives. Currently, he works as Graduate Research Assistant at the Texas Digital Library.  A Michigan native, he previously worked in higher education at the University of Michigan- Ann Arbor, where he earned his bachelor's degree in History."

  ArisWells:
    name: Aris Wells
    prof: false
    gravatar:
    website: "#"
    github: ArisWells
    twitter:
    about: "This is my 3rd semester in the iSchool. My undergraduate studies were in physics but I had (surprisngly minor) exposure to coding in Python in a class called 'Linux and Python'"

  AU-turtledragon:
    name: Aaron Ulmer
    prof: false
    gravatar:
    website: "#"
    github: AU-turtledragon
    twitter:
    about: "Aaron is currently a student of Python at the University of Texas School of Information.  He likes tacos and being left alone - unless you have tacos."

  benderliz:
    name: benderliz
    prof: false
    gravatar:
    website: "#"
    github: benderliz
    twitter: betweenthelibs
    about: "Liz is a first-year dual degree MA in English and MS in Information Studies student at UT Austin. Her research interests lie at the intersection of language, technology, and culture. She enjoys reading, hiking, going to museums, and reviewing ice cream parlors on Instagram."

  boyeonpark:
    name: boyeonpark
    prof: false
    gravatar:
    website: "#"
    github: boyeonpark
    twitter:
    about: "Here's a little about boyeonpark"

  choim7:
    name: choim7
    prof: false
    gravatar:
    website: "#"
    github: choim7
    twitter: choimwd
    about: "Hi, I want Lego for Christmas present:)"

  cmr4658:
    name: Chase Rigby
    prof: false
    gravatar:
    website:
    github: cmr4658
    twitter:
    about: "Chase is a first-year MSIS student at the iSchool and works in the captioning group at UT Libraries. He is interested in UX research/design and accessibility. Also, he enjoys writing, knitting, and hiking. :running:"

  cridley17:
    name: Claire Ridley
    prof: false
    gravatar:
    website: "#"
    github: cridley17
    twitter:
    about: "Claire is a second year MSIS student concentrating in Archives and Preservation."

  Elizard0926:
    name: Elizard0926
    prof: false
    gravatar:
    website: "https://leelizabeth0926.wixsite.com/website-1"
    github: Elizard0926
    twitter:
    about: "Elizabeth is a first-year student in the iSchool doctoral program. It is her personal mission to do puzzles with no less than 1000 pieces."

  hdubbe:
    name: Hannah Dubbe
    prof: false
    gravatar:
    website: 
    github: hdubbe
    twitter:
    about: "Hannah is a second year MSIS student with a focus on data science. She has a white cat named Sweet Merle."

  IMBLAH:
    name: Bo Zhang
    prof: false
    gravatar:
    website: "#"
    github: IMBLAH
    twitter:
    about: "Bo is in her first year of the MSIS program at the iSchool. She's not a good speaker but a good listener. :)"

  itohosagie:
    name: Itohan Osagie
    prof: false
    gravatar:
    website: "#"
    github: itohosagie
    twitter: 
    about: "Current MSIS student in her second year. Living in Austin, TX. Trying to kick her coffee addiction :coffee:, but keeps failing. New to programming, but excited to learn!"

  lulomax:
    name: Lucius
    prof: false
    gravatar:
    website: "#"
    github: lulomax
    twitter:
    about: "Lucius is a second-year, interested in Health Care."

  sarahva47:
    name: sarahva47
    prof: false
    gravatar:
    website: https://www.linkedin.com/in/sarah-varenhorst-6b2100129/ 
    github: sarahva47
    twitter: SarahAV47
    about: "Sarah Varenhorst (she/her/hers) is a second year in the ISchool. She has two cats named Marie and Oliver, and is a major Swiftie."

  scyrill:
    name: Stephanie C. Cyrill
    prof: false
    gravatar: 
    website: "#"
    github: scyrill
    about: "Hi, I'm Stephanie! I'm a second-year graduate student at the University of Texas at Austin's School of Information with a focus on UX Design and Health Informatics. Learn more about me here!"

  sj-roh:
    name: sj-roh
    prof: false
    gravatar:
    website: "#"
    github: sj-roh
    twitter:
    about: "SJ Roh is a second year graduate student pursuing his Master of Science degree in Information Studies with a focus in Data Science at the School of Information. 
    Prior to his master's studies, he graduated with a Bachelor's degree in Information Sciences and Technology at Penn State University. SJ enjoys playing sports, listening to music, 
    watching Disney shows & films, and shopping."

  spinachleaf:
    name: spinachleaf
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Spinach"
    github: spinachleaf
    twitter: "https://twitter.com/search?q=%23spinach"
    about: "spinachleaf is a green leafy vegetable."

  srj1220:
    name: srj1220
    prof: false
    gravatar:
    website: "#"
    github: srj1220
    twitter:
    about: "Here's a little about srj1220"

  vannyyeh:
    name: vannyyeh
    prof: false
    gravatar:
    website: "https://github.com/vannyyeh"
    github: vannyyeh
    twitter: N/A
    about: "First year in MSIS program, interested in Front-end, a schnauzer lover too!"

  weifeng0102:
    name: weifeng0102
    prof: false
    gravatar:
    website: "#"
    github: weifeng0102
    twitter:
    about: "Here's a little about weifeng0102"

  YitongFeng726:
    name: YitongFeng726
    prof: false
    gravatar:
    website: "#"
    github: YitongFeng726
    twitter:
    about: "Here's a little about YitongFeng726"

  zheinsohn:
    name: Zoe
    prof: false
    gravatar:
    website:
    github: zheinsohn
    twitter:
    about: "Zoe is a second-year MSIS student with a focus on archives and digital humanities."


baseurl:
url:
