name: INF 380P Fall 2020

title: INF 380P

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/Chicago

github_repo_url: https://github.com/inf380p/inf380p.github.io
gitter_room: inf380p/fall2021
zoom_url: https://utexas.zoom.us/j/97095588089


plugins:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Don't serve these files/dirs.
exclude: [vendor, script]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - materials
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

# If this gets archived at a different URL make sure to delete the blank statements at the bottom
baseurl: /fall2021
url: /fall2021

python: true

course:
  title: Introduction to Programming
  number: INF 380P
  instructor: Prof. Elliott Hauser
  ta: Misha Coleman
  semester: Fall 2021
  location: "UTA 1.208"

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: https://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  "Elliott Hauser is an Assistant Professor at the UT Austin iSchool.  He's hacking education as one of the cofounders of Trinket.io."

  MishaCienfuegos:
    name: Misha Coleman
    prof: true
    gravatar:
    website:
    github: MishaCienfuegos
    twitter: mishacienfuegos
    about: "Misha is the Teaching Assistant, in her first semester of the MSIS program at the iSchool. Previously, she worked as a software developer, learning to code on the job. She loves exploring the world by bike! :bike:"

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Turtle"
    github: tommytester
    twitter:
    about: "Testin' course websites since 2014."

baseurl:
url:
